MVCBasicApp/Models/TrialModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCBasicApp.Models
{
    public class Items
    {
        public int id { get; set; }
        public string itemName { get; set; }
    }

    public class ItemDatabase : List<Items>
    {
        public ItemDatabase()
        {
            Add(new Items() { id = 1, itemName = "Item1" });
            Add(new Items() { id = 2, itemName = "Item2" });
            Add(new Items() { id = 3, itemName = "Item3" });
            Add(new Items() { id = 4, itemName = "Item4" });
            Add(new Items() { id = 5, itemName = "Item5" });
            Add(new Items() { id = 6, itemName = "Item6" });
            Add(new Items() { id = 7, itemName = "Item7" });
        }
    }
}

MVCBasicApp/Controllers/FrameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCBasicApp.Models;

namespace MVCBasicApp.Controllers
{
        public class FrameController : Controller
    {
        
        // GET: Frame
        public ActionResult Index()
        {
            // return View();
            return View(new ItemDatabase()); //Return different view than default view           
            
        }

        // GET: Frame/Details/5
        public ActionResult Details(int id)
        {
            var item = new ItemDatabase().FirstOrDefault();
            return View(item);
        }

        // GET: Frame/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Frame/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Frame/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Frame/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Frame/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Frame/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MVCBasicApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCBasicApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCBasicApp/Controllers/PotsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCBasicApp.Controllers
{
    public class PotsController : Controller
    {
        // GET: Pots
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVCBasicApp/Views/Frame/Details.cshtml
@model MVCBasicApp.Models.Items

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

@Model.id : @Model.itemName

MVCBasicApp/Views/Frame/DiffView.cshtml
@{
    ViewBag.Title = "DiffView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DiffView</h2>

MVCBasicApp/Views/Frame/Index.cshtml
@model List<MVCBasicApp.Models.Items>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Frames</h2>

<div class="row">
    <div class="col-md-12">
        <h2>Frame 1</h2>
        Total Items are : @Model.Count()

        <ul>
            @foreach(var item in Model.ToList())
            {
                <li>@item.id : @item.itemName</li>
            }
        </ul>
    </div>
   
</div>

MVCBasicApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCBasicApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCBasicApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Home Decor</h1>
 <!--   <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>-->
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Decor idea 1</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Decor idea 2</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Decor idea 3</h2>
       <!--<p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>--> 
    </div>
</div>

MVCBasicApp/Views/Pots/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Pots Page</h2>

MVCBasicApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home Decor", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Frames", "Index", "Frame")</li>
                    <li>@Html.ActionLink("Pots","Index","Pots")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Tejaswini</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>